
set(WORKSPACE_NAME "WorkspaceName")
set(APP_NAME "AppName")
set(ENGINE_NAME "EngineName")

# COMMON OUTPUT DIRS
set(DEBUG_OUTPUT_DIR ${CMAKE_BINARY_DIR}/bin/Debug)
set(RELEASE_OUTPUT_DIR ${CMAKE_BINARY_DIR}/bin/Release)

# APP
set(APP_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${APP_NAME})
set(APP_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${APP_NAME})
# ENGINE
set(ENGINE_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME})
set(ENGINE_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME})

# GLAD
set(GLAD_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME}/vendor/glad)
set(GLAD_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME}/glad)
# GLFW
set(GLFW_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME}/vendor/glfw)
set(GLFW_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME}/glfw)
# GLM
set(GLM_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME}/vendor/glm)
set(GLM_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME}/glm)
# imgui
set(IMGUI_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME}/vendor/imgui)
set(IMGUI_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME}/imgui)
# stb
set(STB_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME}/vendor/stb)
set(STB_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME}/stb)
# assimp
set(ASSIMP_OUTPUT_DIRECTORY_DEBUG ${DEBUG_OUTPUT_DIR}/${ENGINE_NAME}/vendor/assimp)
set(ASSIMP_OUTPUT_DIRECTORY_RELEASE ${RELEASE_OUTPUT_DIR}/${ENGINE_NAME}/assimp)